import Head from 'next/head';
import { useState } from 'react';
import styles from '../styles/Home.module.css';
import axios from 'axios';
import { SearchInput } from 'evergreen-ui';
import { getSearch } from '../services/api';

export default function Home() {
  const [images, setImages] = useState();
  const handleSearch = (text) => {
   getSearch(text)
    .then((res) => setImages(res?.data))
    .catch((err) => console.log(JSON.stringify(err)))
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>This is index page</p>
        <SearchInput
          placeholder='search'
          onChange={(e) => handleSearch(e.target.value)} 
        />
        
        <div style={{display: 'flex', flexWrap: 'wrap', flexDirection: "row", marginTop: "2em", width: "100%"}}>
          {images?.photos?.map((image) => (
          
            <img style={{width: "20%", marginBottom: '30px', marginRight: '30px'}} src={image.src.tiny} alt={image.alt} />
 
        ))}   
        </div>

          
      </main>

      <footer className={styles.footer}>
        <p>This footer page</p>
      </footer>
    </div>
  )
}
